# Generated by Django 2.2 on 2019-07-15 06:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('photo', models.ImageField(upload_to='Photos/')),
                ('email', models.EmailField(max_length=30)),
                ('mobile', models.CharField(max_length=13)),
                ('designation', models.CharField(max_length=50)),
                ('employee_id', models.IntegerField()),
                ('date_of_joining', models.CharField(max_length=100)),
                ('pan_card_number', models.CharField(max_length=100)),
                ('skills', models.TextField(max_length=500)),
                ('about', models.TextField(max_length=500)),
                ('resume', models.FileField(upload_to='Resume/')),
            ],
        ),
        migrations.CreateModel(
            name='PayslipMonth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payslip_month', models.CharField(max_length=100, unique=True)),
                ('emplyoee_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EmployeeProfile.EmployeeDetails')),
            ],
        ),
        migrations.CreateModel(
            name='SalaryDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pay_period', models.CharField(max_length=100)),
                ('pay_date', models.CharField(max_length=100)),
                ('basic_salary', models.IntegerField()),
                ('performance_allowance', models.IntegerField()),
                ('bonus_allowance', models.IntegerField()),
                ('account_number', models.IntegerField()),
                ('ifsc_code', models.CharField(max_length=100)),
                ('payslip_month', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EmployeeProfile.PayslipMonth')),
            ],
        ),
    ]
